// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using finance_scraper_1.Models;

namespace financescraper1.Migrations
{
    [DbContext(typeof(MvcStockContext))]
    partial class MvcStockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("finance_scraper_1.Models.Stocks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AvgVol");

                    b.Property<string>("Change");

                    b.Property<string>("Date");

                    b.Property<string>("LastPrice");

                    b.Property<string>("MarketCap");

                    b.Property<string>("MarketTime");

                    b.Property<string>("PercentChange");

                    b.Property<string>("Shares");

                    b.Property<string>("Symbol");

                    b.Property<string>("Volume");

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
